### ISSUE TITLE
GitHub Actions 运行，第二天就会报cookie过期，连续试了3天，都是如此

### ISSUE THREAD

**Issue by dlNone** [findmover/wxread#16]
尝试第 1 次阅读...
***'errCode': -2012, 'errMsg': '登录超时', 'errLog': 'C8yl2bO', 'info': ''***
❌ cookie 已过期，尝试刷新...
✅ 密钥刷新成功，新密钥：Q0cAEu9l
🔄 重新本次阅读。

**Comment by findmover** [comment]
cookie过期正常的，阅读cookie一个小时左右刷一次，只要阅读进度在增加就没事。

**Comment by dlNone** [comment]
我一直输出的是同样的信息，阅读时长也没有增加。
![image](https://github.com/user-attachments/assets/c1073f21-7597-442b-bf6f-e557788ee27d)

**Comment by findmover** [comment]
是不是抓包的有问题
加我vx：life_cypher,帮你看一下
