### ISSUE TITLE
[求助]如何抓包

### ISSUE THREAD

**Issue by 46fafa** [findmover/wxread#17]
作者您好，关于如何抓包的部分能否详细一些，谢谢！
完全不懂代码的小白，不知道该从那里找到cookie等信息。
![image](https://github.com/user-attachments/assets/7b86bb65-5b19-4c8b-abf2-a21b5f7720fd)

**Comment by findmover** [comment]
你的方法没啥问题，没抓到read接口，点击【下一章】抓到read接口复制为bash然后到我提供的那个网站转化为字典格式。
![image](https://github.com/user-attachments/assets/a6fac175-9966-4f8e-835c-9bf95beb62e0)

**Comment by 46fafa** [comment]
> 你的方法没啥问题，没抓到read接口，不用打断点。点击【下一章】抓到read接口复制为bash然后到我提供的那个网站转化为字典格式。 ![image](https://private-user-images.githubusercontent.com/88070121/389751682-a6fac175-9966-4f8e-835c-9bf95beb62e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MzE5NTgsIm5iZiI6MTczMjYzMTY1OCwicGF0aCI6Ii84ODA3MDEyMS8zODk3NTE2ODItYTZmYWMxNzUtOTk2Ni00ZjhlLTgzNWMtOWJmOTViZWI2MmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE0MzQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYjE4YjcwNzBlYWEyMmMwNDg0YTkyZDMxMTNiNmI1YjIxOWQ2MTUwNjBjZDUzZmI0MTc3ZWY3ZTA2YjdjNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K0c7NUH2_V3xcOYmBFaMbR0LeS_rbT0NvuY0OEzRRuM)

我没有打任何断点，打开开发者工具刷新网页就自动出现断点，在控制台出现这个错误
![image](https://github.com/user-attachments/assets/430c609e-034c-42ee-8799-2f8a7c406c0c)
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 74, 119); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="debugger:///VM1283:58" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">VM1283:58</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' 'nonce-C748B0FD65BAC0A28C292D25A7CB8980' <button class="devtools-link text-button link-style" jslog="Link; context: url; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://weread-1258476243.file.myqcloud.com/</button> <button class="devtools-link text-button link-style" jslog="Link; context: url; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://imgservices-1252317822.image.myqcloud.com/</button> <button class="devtools-link text-button link-style" jslog="Link; context: url; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://midas.gtimg.cn/</button> <button class="devtools-link text-button link-style" jslog="Link; context: url; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://cdn.weread.qq.com/</button> 'report-sample'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 74, 119); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 575px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | injectViaScriptTag | @ | VM1283:58
-- | -- | -- | --
  | injectFunc | @ | VM1283:71
  | （匿名） | @ | VM1283:79

</span></div>
</body>
</html>

**Comment by findmover** [comment]
这是安全策略问题吧。试一试关闭浏览器油猴脚本或者插件扩展，或换一个浏览器抓包。

**Comment by leinad59** [comment]
> 这是安全策略问题吧。试一试关闭浏览器油猴脚本或者插件扩展，或换一个浏览器抓包。

这是微信读书的前端为了防止别人调试网站做的安全措施，可以去“源代码/Sources”tab，关闭断点

![image](https://github.com/user-attachments/assets/343321a9-c674-43dd-a644-f39de5c6f9b9)

**Comment by 46fafa** [comment]
> > 这是安全策略问题吧。试一试关闭浏览器油猴脚本或者插件扩展，或换一个浏览器抓包。
> 
> 这是微信读书的前端为了防止别人调试网站做的安全措施，可以去“源代码/Sources”tab，关闭断点
> 
> ![image](https://private-user-images.githubusercontent.com/60702016/390210660-343321a9-c674-43dd-a644-f39de5c6f9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTk2NDIsIm5iZiI6MTczMjcxOTM0MiwicGF0aCI6Ii82MDcwMjAxNi8zOTAyMTA2NjAtMzQzMzIxYTktYzY3NC00M2RkLWE2NDQtZjM5ZGU1YzZmOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE0NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MjY0ZWQyNjc0ZjE0ZGE1MDM1YzAzYmViOGEwYmZmMDc2NGRjNTI3ZjhiZGFjM2M5ZWVhMDFhMzMwMzQwM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H-jIVYtjzde1pQP4QN0UeaHdaoQxHlmgPNIM-rS0duA)

感谢，已经成功解决

**Comment by 46fafa** [comment]
> 这是安全策略问题吧。试一试关闭浏览器油猴脚本或者插件扩展，或换一个浏览器抓包。

感谢作者🙏
