### ISSUE TITLE
cookie有效期最长多久

### ISSUE THREAD

**Issue by liujunjia1996** [findmover/wxread#5]
不知道有人测试过吗

**Comment by findmover** [comment]
从开发这个脚本，进一个月没有掉，以后不清楚

**Comment by findmover** [comment]
从开发这个脚本，近一个月没有掉，以后不清楚
![Screenshot_2024-10-27-22-44-34-463_com tencent weread](https://github.com/user-attachments/assets/28515c11-e5cc-498c-9149-75dc7da46a1a)

**Comment by liujunjia1996** [comment]
> 从开发这个脚本，近一个月没有掉，以后不清楚 ![Screenshot_2024-10-27-22-44-34-463_com tencent weread](https://private-user-images.githubusercontent.com/88070121/380506191-28515c11-e5cc-498c-9149-75dc7da46a1a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDE0ODQsIm5iZiI6MTczMDA0MTE4NCwicGF0aCI6Ii84ODA3MDEyMS8zODA1MDYxOTEtMjg1MTVjMTEtZTVjYy00OThjLTkxNDktNzVkYzdkYTQ2YTFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE0NTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNjM2ZjdmYmY3MDlkMmI3NGEyNTg1ZmM4ZTIwOGJmOTRhMjE4ZThhZjhjNmRjOTJhYzVlNmMxMzk0NjU3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1s3ZgUM2BWrAN1IIkHpwaeQzmSY-v58b2ftlT23tUkw)

那也还行了，一个月维护一次也不错。提个小建议，如果header和cookie在main.py和cookie.py里值是一样的话，是否可以提到一个公共的文件中

**Comment by findmover** [comment]
可以后面更新一版
